### ISSUE TITLE
Unhandled exception. System.NotSupportedException: Cannot show selection prompt since the current terminal does not support ANSI escape sequences.

### ISSUE THREAD

**Issue by greenozon** [kiraio-moe/USSR#27]
Subject when running the tool itself

is it possible to add support for it somehow?
THanks

I"ve tried both cmd.exe as well as powershell one

```
PS C:\123> .\USSR.exe
Unity Splash Screen Remover v1.1.8

USSR is a tool to easily remove Unity splash screen. USSR didn't directly "hack" the Unity Editor, but the generated build.

Before using USSR, make sure you have set the splash screen Draw Mode in Player Settings to All Sequential and backup the target file below! For more information, visit USSR GitHub repo:
https://github.com/kiraio-moe/USSR

HOW TO USE
Select the action below, find and select one of these files in your game data:
globalgamemanagers | data.unity3d | *.data | *.data.br | *.data.gz | *.data.unityweb


Unhandled exception. System.NotSupportedException: Cannot show selection prompt since the current terminal does not support ANSI escape sequences.
   at Spectre.Console.ListPrompt`1.Show(ListPromptTree`1 tree, SelectionMode selectionMode, Boolean skipUnselectableItems, Boolean searchEnabled, Int32 requestedPageSize, Boolean wrapAround, Cancellat
ionToken cancellationToken) in /_/src/Spectre.Console/Prompts/List/ListPrompt.cs:line 38
   at Spectre.Console.SelectionPrompt`1.ShowAsync(IAnsiConsole console, CancellationToken cancellationToken) in /_/src/Spectre.Console/Prompts/SelectionPrompt.cs:line 102
   at Spectre.Console.SelectionPrompt`1.Show(IAnsiConsole console) in /_/src/Spectre.Console/Prompts/SelectionPrompt.cs:line 94
   at Spectre.Console.AnsiConsole.Prompt[T](IPrompt`1 prompt) in /_/src/Spectre.Console/AnsiConsole.Prompt.cs:line 21
   at USSR.Core.USSR.GetPromptChoice(String[] menuList) in E:\Projects\DOTNET\USSR\USSR.cs:line 360
   at USSR.Core.USSR.Main(String[] args) in E:\Projects\DOTNET\USSR\USSR.cs:line 27
```

**Comment by kiraio-moe** [comment]
Hi, run USSR on Terminal, CMD or PowerShell. It's not supported on Git Bash.

**Comment by greenozon** [comment]
Thanks
