### ISSUE TITLE
[BUG] Unhandled Exception: Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by yywfyb** [kiraio-moe/USSR#6]
Unity Splash Screen Remover v1.1.3
Loading class type package...
Found globalgamemanagers.
Loading globalgamemanagers and it's dependencies...
Loading asset class types database...
Unhandled exception. System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetsTools.NET.AssetsFileReader.ReadInt32()
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField, RefTypeManager refMan)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField, RefTypeManager refMan)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField, RefTypeManager refMan)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField, RefTypeManager refMan)
   at AssetsTools.NET.AssetTypeTemplateField.MakeValue(AssetsFileReader reader, RefTypeManager refMan)
   at USSR.Program.Main(String[] args) in D:\Projects\USSR\Program.cs:line 18

**Comment by kiraio-moe** [comment]
What's your Unity version? Some Unity version is for 'unknown' reason can't be read.
Try to use other Unity version, you maybe luck.

**Comment by Faithtoken** [comment]
Same for me, except "cs:line 202".
Unity 2023.1.19f

**Comment by ULE7** [comment]
Same for me, I tried about 4 or 5 version of unity 2021, all end up with "**Unable to read beyond the end of the stream**", one is 2021.3.0f1c1, the last one is 2021.1.10f1c1, I pick them randomly though got be one working and it failed me......The only one working  is 2020.1.0f1 which is an already cracked version.
So I turn on the splash logo at 2020.1.0 and made a webgl package, the USSR looked worked fine, However when I tried to open this webgl program it got stuck somehow, and never entered inside program. By the way I am using 1.1.5 USSR, already choose "All Sequential".

**Comment by kiraio-moe** [comment]
I have updated USSR, can y'all test it again?

**Comment by UiharuKazari2008** [comment]
Same issue with latest build and Unity 2022.3.13f1

**Comment by Kingo64** [comment]
Same issue with 2023.2.2f1 on v1.1.6
